name: PR Check

on:
  pull_request:
    branches:
      - main
      - develop
      - 'releases/**'
    types:
      - opened
      - synchronize
      - reopened
  merge_group:
    branches:
      - main
      - develop
      - 'releases/**'

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Debug changed files
        run: |
          echo "Измененные файлы: ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Run code quality check
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          API_URL: "https://arrivals-worker-harvest-death.trycloudflare.com/check-quality"
        run: |
          if [ -z "$CHANGED_FILES" ]; then
            echo "Изменения в файлах не обнаружены"
            exit 0
          fi

          echo "Отправляем файлы на проверку: $CHANGED_FILES"
          
          JSON_PAYLOAD=$(jq -n --arg files "$CHANGED_FILES" '{"files": ($files | split(" "))}')
          
          echo "Подготовленные данные: $JSON_PAYLOAD"
          
          RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "$API_URL")
          
          echo "Ответ API: $RESPONSE"
          
          if echo "$RESPONSE" | jq -e '.status == "success"' > /dev/null; then
            echo "Проверка пройдена успешно"
            exit 0
          else
            echo "Проверка не пройдена"
            echo "Детали: $(echo "$RESPONSE" | jq -r '.details // .message')"
            exit 1
          fi